const DETAIL_ACTIONS = {
  UPDATE_GAS_STATION_DETAIL: "UPDATE_GAS_STATION_DETAIL"
};

const LIST_ACTIONS = {
  UPDATE_GAS_STATION_LIST: "UPDATE_GAS_STATION_LIST"
};

const ACTIONS = {
  UPDATE_STATE: "UPDATE_STATE"
};

export { DETAIL_ACTIONS, LIST_ACTIONS, ACTIONS };
