const DETAIL_ACTIONS = {
  UPDATE_GAS_STATION_DETAIL: "UPDATE_GAS_STATION_DETAIL"
};

const LIST_ACTIONS = {
  UPDATE_GAS_STATION_LIST: "UPDATE_GAS_STATION_LIST"
};

const APP_ACTIONS = {
  UPDATE_LOADING: "UPDATE_LOADING"
};

export { DETAIL_ACTIONS, LIST_ACTIONS, APP_ACTIONS };
