name: Node.js CICD

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true
    - name: Deploy to gh-pages
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run deploy --name="deploy-bot" --email="7jgjung@gmail.com"
      
